ARG image=node
ARG version=16.20-bullseye


FROM ${image}:${version}

RUN mkdir /app
WORKDIR /app

COPY package.json /app
COPY package-lock.json /app

RUN npm ci --no-audit

COPY tsconfig.base.json /app
COPY nx.json /app


