## Docker compose file containing the following services:
## - nginx
## - postgres database
## - kafka

version: '2'
services:
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  postgres:
    image: 'postgres:16rc1-bullseye'
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mytopsecretpassword
      - POSTGRES_DB=postgres
  product-service:
    restart: always
    env_file:
      - ./apps/product-service/.env.docker
    environment:
      - PRODUCT_SERVICE_API_PORT=3001
    build:
      context: .
      dockerfile: Dockerfile.compose
    volumes:
      - ./apps/product-service:/app/apps/product-service
    ports:
      - 3001:3001
    command: npx nx serve product-service
    depends_on:
      - postgres
  order-service:
    restart: always
    env_file:
      - ./apps/order-service/.env.docker
    environment:
      - ORDER_SERVICE_API_PORT=3002
    build:
      context: .
      dockerfile: Dockerfile.compose
    volumes:
      - ./apps/order-service:/app/apps/order-service
    ports:
      - 3002:3002
    command: npx nx serve order-service
    depends_on:
      - postgres
  user-service:
    restart: always
    env_file:
      - ./apps/order-service/.env.docker
    environment:
      - USER_SERVICE_API_PORT=3003
    build:
      context: .
      dockerfile: Dockerfile.compose
    volumes:
      - ./apps/user-service:/app/apps/user-service
    ports:
      - 3003:3003
    command: npx nx serve user-service
    depends_on:
      - postgres
  nginx:
    image: 'nginx:latest'
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - product-service
      - order-service
      - user-service
